### ISSUE TITLE
Can't login to GUI

### ISSUE THREAD

**Issue by nick51502** [fastogt/fastonosql#78]
Whenever I try and login to the FastNoSQL GUI (Windows 10), it gives this error "Sorry can't connect to server, for checking your credentials."

**Comment by topilski** [comment]
Hey, let's check

**Comment by topilski** [comment]
You need to check your firewalls

**Comment by cache-sk** [comment]
Just a little note. The user needs a client to connect to such services mostly at work. In a work environment, dubious url and non-standard ports are often blocked. Since I can't try the 1-day trial at my work, because I can't connect to your server to verify the login, this client is absolutely useless.

So the "check your firewall" response is absurd. No, you check if you are using standard ports or something obscurd that is normally forbidden.
